package types

import "time"

// User represents a Telegram user registered in the system
type User struct {
	UID      int64     `json:"uid"`       // Telegram UID
	Role     string    `json:"role"`      // Role: "master" or "sub"
	Name     string    `json:"name"`      // Telegram display name (FirstName + LastName)
	JoinedAt time.Time `json:"joined_at"` // Join timestamp
}

// Token represents an invite activation code generated by the Master
type Token struct {
	Hash      string    `json:"hash"`       // Random hash code
	MaxUses   int       `json:"max_uses"`    // Remaining allowed usages
	UsedCount int       `json:"used_count"`  // Count of times this token has been used
	CreatedBy int64     `json:"created_by"`  // UID of the Master who created it
	CreatedAt time.Time `json:"created_at"`  // Creation timestamp
}

// ServerNode represents a managed gopass-agent node
type ServerNode struct {
	Alias     string       `json:"alias"`      // Node identifier name (e.g. "test-server-1")
	Connected bool         `json:"connected"`  // Connection status of Agent
	LastSeen  time.Time    `json:"last_seen"`  // Timestamp of last received heartbeat
	Hardware  HardwareInfo `json:"hardware"`   // Snapshot of hardware usage
	IP        string       `json:"ip"`         // Connection IP
}

// HardwareInfo details cpu, memory and disk usage metrics
type HardwareInfo struct {
	CPUUsage    float64 `json:"cpu_usage"`    // CPU usage percentage
	MemoryUsage float64 `json:"memory_usage"` // Memory usage percentage
	DiskUsage   float64 `json:"disk_usage"`   // Disk usage percentage
}
