package types

import "time"

// User represents a Telegram user registered in the system
type User struct {
	UID         int64           `json:"uid"`         // Telegram UID
	Role        string          `json:"role"`        // Role: "master", "admin" or "sub"
	Name        string          `json:"name"`        // Telegram display name
	JoinedAt    time.Time       `json:"joined_at"`   // Join timestamp
	Permissions map[string]bool `json:"permissions"` // RBAC permissions map
	AssignedCF  string          `json:"assigned_cf"` // Assigned CF Config ID
}

// Permission Constants
const (
	PermCFConfig    = "cf_config"
	PermCFAllocate  = "cf_allocate"
	PermCheckUpdate = "check_update"
	PermInvite      = "invite"
	PermSetAdmin    = "set_admin"
)

// CFConfig represents an isolated Cloudflare API Configuration
type CFConfig struct {
	ID                string    `json:"id"`                    // Unique ID for the config (e.g., UUID)
	Name              string    `json:"name"`                  // User-defined alias
	APIToken          string    `json:"api_token"`             // CF API Token
	ZoneID            string    `json:"zone_id"`               // CF Zone ID
	R2AccessKeyID     string    `json:"r2_access_key_id,omitempty"`    // R2 Access Key ID
	R2SecretAccessKey string    `json:"r2_secret_access_key,omitempty"` // R2 Secret Access Key
	R2Endpoint        string    `json:"r2_endpoint,omitempty"`         // R2 Endpoint
	CreatedBy         int64     `json:"created_by"`            // UID of the admin who created it
	CreatedAt         time.Time `json:"created_at"`
}

// Token represents an invite activation code generated by the Master
type Token struct {
	Hash      string    `json:"hash"`       // Random hash code
	MaxUses   int       `json:"max_uses"`    // Remaining allowed usages
	UsedCount int       `json:"used_count"`  // Count of times this token has been used
	CreatedBy int64     `json:"created_by"`  // UID of the Master who created it
	CreatedAt time.Time `json:"created_at"`  // Creation timestamp
}

// ServerNode represents a managed gopass-agent node
type ServerNode struct {
	Alias     string       `json:"alias"`      // Node identifier name (e.g. "test-server-1")
	Connected bool         `json:"connected"`  // Connection status of Agent
	LastSeen  time.Time    `json:"last_seen"`  // Timestamp of last received heartbeat
	Hardware  HardwareInfo `json:"hardware"`   // Snapshot of hardware usage
	IP        string       `json:"ip"`         // Connection IP
}

// HardwareInfo details cpu, memory and disk usage metrics
type HardwareInfo struct {
	CPUUsage    float64 `json:"cpu_usage"`    // CPU usage percentage
	MemoryUsage float64 `json:"memory_usage"` // Memory usage percentage
	DiskUsage   float64 `json:"disk_usage"`   // Disk usage percentage
}
