// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: pkg/proto/protocol.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Progress
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_pkg_proto_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetProgress() *TaskProgress {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Progress struct {
	Progress *TaskProgress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_Progress) isAgentMessage_Payload() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_proto_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	DiskUsage     float64                `protobuf:"fixed64,4,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_pkg_proto_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_pkg_proto_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Heartbeat) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Heartbeat) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *Heartbeat) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

type TaskProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "CLONING", "BUILDING", "ROUTING", "SUCCESS", "FAILED"
	LogLine       string                 `protobuf:"bytes,3,opt,name=log_line,json=logLine,proto3" json:"log_line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskProgress) Reset() {
	*x = TaskProgress{}
	mi := &file_pkg_proto_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgress) ProtoMessage() {}

func (x *TaskProgress) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgress.ProtoReflect.Descriptor instead.
func (*TaskProgress) Descriptor() ([]byte, []int) {
	return file_pkg_proto_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *TaskProgress) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskProgress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TaskProgress) GetLogLine() string {
	if x != nil {
		return x.LogLine
	}
	return ""
}

type MasterMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MasterMessage_RegisterResponse
	//	*MasterMessage_DeployTask
	//	*MasterMessage_UpdateAgentTask
	Payload       isMasterMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterMessage) Reset() {
	*x = MasterMessage{}
	mi := &file_pkg_proto_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterMessage) ProtoMessage() {}

func (x *MasterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterMessage.ProtoReflect.Descriptor instead.
func (*MasterMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *MasterMessage) GetPayload() isMasterMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MasterMessage) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *MasterMessage) GetDeployTask() *DeployTask {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_DeployTask); ok {
			return x.DeployTask
		}
	}
	return nil
}

func (x *MasterMessage) GetUpdateAgentTask() *UpdateAgentTask {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_UpdateAgentTask); ok {
			return x.UpdateAgentTask
		}
	}
	return nil
}

type isMasterMessage_Payload interface {
	isMasterMessage_Payload()
}

type MasterMessage_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,1,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type MasterMessage_DeployTask struct {
	DeployTask *DeployTask `protobuf:"bytes,2,opt,name=deploy_task,json=deployTask,proto3,oneof"`
}

type MasterMessage_UpdateAgentTask struct {
	UpdateAgentTask *UpdateAgentTask `protobuf:"bytes,3,opt,name=update_agent_task,json=updateAgentTask,proto3,oneof"`
}

func (*MasterMessage_RegisterResponse) isMasterMessage_Payload() {}

func (*MasterMessage_DeployTask) isMasterMessage_Payload() {}

func (*MasterMessage_UpdateAgentTask) isMasterMessage_Payload() {}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_proto_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DeployTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	GitUrl        string                 `protobuf:"bytes,2,opt,name=git_url,json=gitUrl,proto3" json:"git_url,omitempty"`
	ProjectName   string                 `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	RoutingDomain string                 `protobuf:"bytes,4,opt,name=routing_domain,json=routingDomain,proto3" json:"routing_domain,omitempty"`
	RoutingPort   int32                  `protobuf:"varint,5,opt,name=routing_port,json=routingPort,proto3" json:"routing_port,omitempty"`
	Env           map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UseSsl        bool                   `protobuf:"varint,7,opt,name=use_ssl,json=useSsl,proto3" json:"use_ssl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployTask) Reset() {
	*x = DeployTask{}
	mi := &file_pkg_proto_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployTask) ProtoMessage() {}

func (x *DeployTask) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployTask.ProtoReflect.Descriptor instead.
func (*DeployTask) Descriptor() ([]byte, []int) {
	return file_pkg_proto_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *DeployTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DeployTask) GetGitUrl() string {
	if x != nil {
		return x.GitUrl
	}
	return ""
}

func (x *DeployTask) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *DeployTask) GetRoutingDomain() string {
	if x != nil {
		return x.RoutingDomain
	}
	return ""
}

func (x *DeployTask) GetRoutingPort() int32 {
	if x != nil {
		return x.RoutingPort
	}
	return 0
}

func (x *DeployTask) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *DeployTask) GetUseSsl() bool {
	if x != nil {
		return x.UseSsl
	}
	return false
}

type UpdateAgentTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl   string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	GithubToken   string                 `protobuf:"bytes,2,opt,name=github_token,json=githubToken,proto3" json:"github_token,omitempty"`
	TagName       string                 `protobuf:"bytes,3,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentTask) Reset() {
	*x = UpdateAgentTask{}
	mi := &file_pkg_proto_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentTask) ProtoMessage() {}

func (x *UpdateAgentTask) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentTask.ProtoReflect.Descriptor instead.
func (*UpdateAgentTask) Descriptor() ([]byte, []int) {
	return file_pkg_proto_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAgentTask) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *UpdateAgentTask) GetGithubToken() string {
	if x != nil {
		return x.GithubToken
	}
	return ""
}

func (x *UpdateAgentTask) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

var File_pkg_proto_protocol_proto protoreflect.FileDescriptor

const file_pkg_proto_protocol_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/proto/protocol.proto\x12\bprotocol\"\xbd\x01\n" +
	"\fAgentMessage\x127\n" +
	"\bregister\x18\x01 \x01(\v2\x19.protocol.RegisterRequestH\x00R\bregister\x123\n" +
	"\theartbeat\x18\x02 \x01(\v2\x13.protocol.HeartbeatH\x00R\theartbeat\x124\n" +
	"\bprogress\x18\x03 \x01(\v2\x16.protocol.TaskProgressH\x00R\bprogressB\t\n" +
	"\apayload\"=\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x80\x01\n" +
	"\tHeartbeat\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x01R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x04 \x01(\x01R\tdiskUsage\"X\n" +
	"\fTaskProgress\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x19\n" +
	"\blog_line\x18\x03 \x01(\tR\alogLine\"\xe7\x01\n" +
	"\rMasterMessage\x12I\n" +
	"\x11register_response\x18\x01 \x01(\v2\x1a.protocol.RegisterResponseH\x00R\x10registerResponse\x127\n" +
	"\vdeploy_task\x18\x02 \x01(\v2\x14.protocol.DeployTaskH\x00R\n" +
	"deployTask\x12G\n" +
	"\x11update_agent_task\x18\x03 \x01(\v2\x19.protocol.UpdateAgentTaskH\x00R\x0fupdateAgentTaskB\t\n" +
	"\apayload\"Q\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xad\x02\n" +
	"\n" +
	"DeployTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\agit_url\x18\x02 \x01(\tR\x06gitUrl\x12!\n" +
	"\fproject_name\x18\x03 \x01(\tR\vprojectName\x12%\n" +
	"\x0erouting_domain\x18\x04 \x01(\tR\rroutingDomain\x12!\n" +
	"\frouting_port\x18\x05 \x01(\x05R\vroutingPort\x12/\n" +
	"\x03env\x18\x06 \x03(\v2\x1d.protocol.DeployTask.EnvEntryR\x03env\x12\x17\n" +
	"\ause_ssl\x18\a \x01(\bR\x06useSsl\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x0fUpdateAgentTask\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x12!\n" +
	"\fgithub_token\x18\x02 \x01(\tR\vgithubToken\x12\x19\n" +
	"\btag_name\x18\x03 \x01(\tR\atagName2M\n" +
	"\fAgentService\x12=\n" +
	"\x06Tunnel\x12\x16.protocol.AgentMessage\x1a\x17.protocol.MasterMessage(\x010\x01B\x12Z\x10gopass/pkg/protob\x06proto3"

var (
	file_pkg_proto_protocol_proto_rawDescOnce sync.Once
	file_pkg_proto_protocol_proto_rawDescData []byte
)

func file_pkg_proto_protocol_proto_rawDescGZIP() []byte {
	file_pkg_proto_protocol_proto_rawDescOnce.Do(func() {
		file_pkg_proto_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_protocol_proto_rawDesc), len(file_pkg_proto_protocol_proto_rawDesc)))
	})
	return file_pkg_proto_protocol_proto_rawDescData
}

var file_pkg_proto_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_protocol_proto_goTypes = []any{
	(*AgentMessage)(nil),     // 0: protocol.AgentMessage
	(*RegisterRequest)(nil),  // 1: protocol.RegisterRequest
	(*Heartbeat)(nil),        // 2: protocol.Heartbeat
	(*TaskProgress)(nil),     // 3: protocol.TaskProgress
	(*MasterMessage)(nil),    // 4: protocol.MasterMessage
	(*RegisterResponse)(nil), // 5: protocol.RegisterResponse
	(*DeployTask)(nil),       // 6: protocol.DeployTask
	(*UpdateAgentTask)(nil),  // 7: protocol.UpdateAgentTask
	nil,                      // 8: protocol.DeployTask.EnvEntry
}
var file_pkg_proto_protocol_proto_depIdxs = []int32{
	1, // 0: protocol.AgentMessage.register:type_name -> protocol.RegisterRequest
	2, // 1: protocol.AgentMessage.heartbeat:type_name -> protocol.Heartbeat
	3, // 2: protocol.AgentMessage.progress:type_name -> protocol.TaskProgress
	5, // 3: protocol.MasterMessage.register_response:type_name -> protocol.RegisterResponse
	6, // 4: protocol.MasterMessage.deploy_task:type_name -> protocol.DeployTask
	7, // 5: protocol.MasterMessage.update_agent_task:type_name -> protocol.UpdateAgentTask
	8, // 6: protocol.DeployTask.env:type_name -> protocol.DeployTask.EnvEntry
	0, // 7: protocol.AgentService.Tunnel:input_type -> protocol.AgentMessage
	4, // 8: protocol.AgentService.Tunnel:output_type -> protocol.MasterMessage
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_proto_protocol_proto_init() }
func file_pkg_proto_protocol_proto_init() {
	if File_pkg_proto_protocol_proto != nil {
		return
	}
	file_pkg_proto_protocol_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Progress)(nil),
	}
	file_pkg_proto_protocol_proto_msgTypes[4].OneofWrappers = []any{
		(*MasterMessage_RegisterResponse)(nil),
		(*MasterMessage_DeployTask)(nil),
		(*MasterMessage_UpdateAgentTask)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_protocol_proto_rawDesc), len(file_pkg_proto_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_protocol_proto_goTypes,
		DependencyIndexes: file_pkg_proto_protocol_proto_depIdxs,
		MessageInfos:      file_pkg_proto_protocol_proto_msgTypes,
	}.Build()
	File_pkg_proto_protocol_proto = out.File
	file_pkg_proto_protocol_proto_goTypes = nil
	file_pkg_proto_protocol_proto_depIdxs = nil
}
